# MEINKRAFT
# created by jaylawl
#
# SpigotMC: https://www.spigotmc.org/resources/meinkraft.74914/
# Github-page: https://github.com/jaylawl/MEINKRAFT/issues
#
# (de-)activating commands and/or modules requires a server-restart
#
# Permissions:
# - base permission to access tab completion and feedback of command:   "mk.<command>"            (example: "mk.fly")
# - self permission for each command:                                   "mk.<command>.self"       (example: "mk.fly.self")
# - permission to use command effects on all players:                   "mk.<command>.others"     (example: "mk.fly.others")
#
# - permission for master command:                                      "mk.admin"
# - commands with only one permission:
#     /query
#     /statistic
#

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Commands:
  fly: true
  gm: true
  godmode: true
  heal: true
  inventoryspy: true
  nightvision: true
  ping: true
  query: true
  speed: true
  statistic: true
  world: true

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
