main: de.jaylawl.meinkraft.Meinkraft
name: MEINKRAFT
version: 1.3.0
api-version: "1.17"
author: jaylawl
description: Lightweight library of commands & tools

commands:

  meinkraft:
    aliases: [ mk ]

  fly:
  gm:
  godmode:
    aliases: [ god ]
  heal:
  inventoryspy:
    aliases: [ invspy, invsee ]
  nightvision:
    aliases: [ nv ]
  ping:
  query:
  speed:
  statistic:
    aliases: [ stat ]
  world: