main: de.jaylawl.meinkraft.Main
name: MEINKRAFT
version: 1.0.3
api-version: "1.14"
author: jaylawl
description: Lightweight library of admin tools
commands:
  mk:
    description: Master command
  fly:
    description: " "
  gm:
    description: " "
  god:
    description: " "
  heal:
    description: " "
  invsee:
    description: " "
  ping:
    description: " "
  speed:
    description: " "
  world:
    description: " "