main: de.jaylawl.meinkraft.Main
name: MEINKRAFT
version: 0.dev8
api-version: "1.14"
author: jaylawl
description: Lightweight library of essential commands
commands:
  mk:
    description: Master command
  fly:
    description: " "
  gm:
    description: " "
  invsee:
    description: " "
  ping:
    description: " "
  speed:
    description: " "
  god:
    description: " "
  world:
    description: " "