main: de.jaylawl.meinkraft.Meinkraft
name: MEINKRAFT
version: 1.1.0
api-version: "1.16"
author: jaylawl
description: Lightweight library of admin tools
commands:
  meinkraft:
    aliases: [mk]
    permission: "mk.admin"
    description: "Master command"
  fly:
    permission: "mk.fly"
  gm:
    permission: "mk.gamemode"
  god:
    permission: "mk.god"
  heal:
    permission: "mk.heal"
  invsee:
    permission: "mk.invsee"
  nightvision:
    aliases: [nv]
    permission: "mk.nightvision"
  ping:
    permission: "mk.ping"
  query:
    permission: "mk.query"
  speed:
    permission: "mk.speed"
  stat:
    permission: "mk.stat"
  world:
    permission: "mk.world"