main: de.jaylawl.meinkraft.MEINKRAFT
name: MEINKRAFT
version: 1.0.5
api-version: "1.14"
author: jaylawl
description: Lightweight library of admin tools
commands:
  mk:
    description: Master command
  fly:
    description: " "
  gm:
    description: " "
  god:
    description: " "
  heal:
    description: " "
  invsee:
    description: " "
  nightvision:
    description: " "
    aliases: [nv]
  ping:
    description: " "
  query:
    description: " "
  speed:
    description: " "
  world:
    description: " "